#!/bin/sh

#  Copyright (C) 2014,2015 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0

# U-Boot systems boot time initializations

init_arch()
{

############################################################
#
    env_sz="0x10000"

    mtd=$(grep nenv /proc/mtd | sed -e 's/:.*$//')
    [ -c "/dev/$mtd" ] || {
        log_failure_msg "Unable to find u-boot environment mtd device: /dev/$mtd"
        return 1
    }
    sect_sz="0x$(grep nenv /proc/mtd | awk '{print $3}')"
    [ -n "$sect_sz" ] || {
        log_failure_msg "Unable to find u-boot environment mtd erase size"
        return 1
    }

    (cat <<EOF
# MTD device name       Device offset   Env. size       Flash sector size
/dev/$mtd               0x00000000      $env_sz         $sect_sz
EOF
) > /etc/fw_env.config

############################################################
# setup OOB port mac address
    ifconfig eth0 down
    mac=$(onie-syseeprom --get 0x24)
    if [ $? -eq 0 -a -n "$mac" ] ; then
       ifconfig eth0 hw ether $mac
    fi
}

# Local Variables:
# mode: shell-script
# eval: (sh-set-shell "/bin/sh" t nil)
# End:
